language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '14'
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - santi_ga1020@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  cleanup: true
  skip_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit-message: "Deploy del proyecto"
  on:
    branch: master