language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "12"
git:
  depth: 3
script:
  - yarn build
notifications:
  email:
    recipients:
      - santi_ga1020@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  edge: true
  cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master